from colors import *
FPS = 60
WIDTH = 400
HEIGHT = 600

TITLE = 'Dash Avoid'
BGCOLOR = SKYBLUE

PLAYERSIZE = 30

STARTING_ITEMS = 20
ITEMSIZE = 20
ITEMGAP = 50
ITEMSTARTSPEED = 2
ITEMCOLORS = [DARKGREEN, MIDNIGHTBLUE, ORANGE, PURPLE]